<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApparelAccessories</name>
   <tag></tag>
   <elementGuidId>e6144522-5beb-420b-96fa-70a238d70216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_68</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='category_68']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#category_68</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a17600a0-e70b-46a5-a491-6666e26aa6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_68</value>
      <webElementGuid>10df92f4-320d-4c85-a247-228114a5144f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apparel &amp; accessories</value>
      <webElementGuid>7fdeb3c8-d572-41bb-8343-5707e53fa1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_68&quot;)</value>
      <webElementGuid>37669b7d-3777-4ed3-b07a-38c371b318f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='category_68']</value>
      <webElementGuid>2b3097ce-a0a8-40c4-9837-cb7bb8dc14c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='search-category']/li[4]/a</value>
      <webElementGuid>e6c4b35c-d6ee-4046-81ea-ef624d1a1089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apparel &amp; accessories')]</value>
      <webElementGuid>5121b24d-d323-4bd5-ad60-47e763486765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[2]/following::a[1]</value>
      <webElementGuid>f59843de-776d-4a71-83a6-66399a291b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[1]/following::a[2]</value>
      <webElementGuid>97f8e445-ad36-4f94-84d6-e703b918938b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Makeup'])[1]/preceding::a[1]</value>
      <webElementGuid>f6d6ecfb-73f5-4c94-b3be-84fc6edf1a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skincare'])[1]/preceding::a[2]</value>
      <webElementGuid>37a74ce3-a511-4d90-9c75-730cccd25447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apparel &amp; accessories']/parent::*</value>
      <webElementGuid>de770796-fd3a-48b4-8fa6-2a909a93c166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/ul/li[4]/a</value>
      <webElementGuid>b7620353-2291-4821-90df-39d6c558b2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'category_68' and (text() = 'Apparel &amp; accessories' or . = 'Apparel &amp; accessories')]</value>
      <webElementGuid>75c2e632-5ced-4388-b422-0d76d90d4b42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
