<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address1TextBox</name>
   <tag></tag>
   <elementGuidId>852109ae-98c2-4699-9400-8a96ec90499e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestFrm_address_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestFrm_address_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#guestFrm_address_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1db215e1-c1b2-45fb-8611-5ac307b38758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0def12ff-2d58-446e-99a8-d8ded3be291c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_1</value>
      <webElementGuid>1388a93f-dfb4-4106-a272-f5dab0510658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestFrm_address_1</value>
      <webElementGuid>cd94e42e-0c00-4117-9a02-3c6927f14264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>cf78bf33-6eb5-4037-942c-47587631b0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestFrm_address_1&quot;)</value>
      <webElementGuid>6723077c-2b45-49e5-b552-c3e4d75ec52f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestFrm_address_1']</value>
      <webElementGuid>82254dde-a9fe-406d-9df7-404ca32d646e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='guestFrm']/div[2]/fieldset/div[2]/div/input</value>
      <webElementGuid>3d7d2608-9107-4563-9e77-2411264d64b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[2]/div/input</value>
      <webElementGuid>f53081c1-0d5b-4e2f-a4c4-2fd09fc4e461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address_1' and @id = 'guestFrm_address_1']</value>
      <webElementGuid>79b80da1-8275-405b-82a3-935d36e300c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
