<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CityTextBox</name>
   <tag></tag>
   <elementGuidId>1b6273f0-2d4e-4805-8180-5b197b2063a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestFrm_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestFrm_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#guestFrm_city</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d3a0c41-d9da-448f-94fb-85e4fcb61784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dae3ef2d-6c81-4ef4-9c0c-1914e884efbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>2974aafb-6f30-47ca-b402-6c05872fefc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestFrm_city</value>
      <webElementGuid>a8ce6f4c-9db1-4195-8c4e-a59218f39d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>54ba6aac-424d-4b14-8fc8-81924f53808f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestFrm_city&quot;)</value>
      <webElementGuid>c8a7da34-6340-4847-ac85-af23fb4136d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestFrm_city']</value>
      <webElementGuid>fd4f571b-0cc5-4b60-8d83-654e5c49d407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='guestFrm']/div[2]/fieldset/div[4]/div/input</value>
      <webElementGuid>0552262b-d60e-4fd7-9531-381149e2fe29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div[4]/div/input</value>
      <webElementGuid>98a455a8-40dc-4683-8936-68bda9b04d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'city' and @id = 'guestFrm_city']</value>
      <webElementGuid>204b4f19-0e3c-4b7e-afcb-df2bdebafd6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
