<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmailTextBox</name>
   <tag></tag>
   <elementGuidId>15ad05af-557b-4081-ba87-5c126aafda80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestFrm_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestFrm_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#guestFrm_email</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac749bb7-c593-4422-a5c3-67d2d1e2930b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1b93d33-cc5f-4792-ac82-2124e8dfb363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a61db736-a24f-42ea-8f82-ff9227566895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestFrm_email</value>
      <webElementGuid>2cbd7ff8-bc45-44dd-a156-d23e6d39bcda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>7e6be8fa-b8d2-4431-afc7-5ecb939249b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestFrm_email&quot;)</value>
      <webElementGuid>4b6c370f-400c-47a3-a947-6a55654a8c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestFrm_email']</value>
      <webElementGuid>c8c12a19-e31b-4736-b4a7-68d99412e9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='guestFrm']/div/fieldset/div[3]/div/input</value>
      <webElementGuid>f74a38d5-9a00-4f52-990e-4e25973da9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9c12f3d9-ebd6-4abd-b09d-0f18b5014142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @id = 'guestFrm_email']</value>
      <webElementGuid>f0e87927-8c0e-4824-a4d1-f3428876bd56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
