<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FirstNameTextBox</name>
   <tag></tag>
   <elementGuidId>0daf471e-1f55-4b07-8654-6998d0395abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestFrm_firstname</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'firstname' and @id = 'guestFrm_firstname']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestFrm_firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#guestFrm_firstname</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b1477af-963b-4372-94c2-d348a97a9210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eecc0fc-710c-4bf7-b674-f2d7b1ccf92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>487484df-0a04-45ba-bdfb-df70eee30ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestFrm_firstname</value>
      <webElementGuid>24993e93-274e-4346-8958-a2d59ac2823a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>a10012c4-56b7-4dd8-8d95-b75ed4f52242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestFrm_firstname&quot;)</value>
      <webElementGuid>58d9fa18-dec6-45c8-95d7-4dfa7ec1c99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestFrm_firstname']</value>
      <webElementGuid>8f215044-041e-4fbb-967e-d6f206fc2c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='guestFrm']/div/fieldset/div/div/input</value>
      <webElementGuid>0f12048b-3a0b-4b3f-9d94-87212202705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>b0b88c02-6874-4468-9f5d-ac488c11317b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'firstname' and @id = 'guestFrm_firstname']</value>
      <webElementGuid>5ffb3b5b-94c9-4d31-984d-1d6e51480200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
