<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LastNameTextBox</name>
   <tag></tag>
   <elementGuidId>f9b041a2-2a71-4f0d-8dba-b8d60e54303d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guestFrm_lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestFrm_lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#guestFrm_lastname</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b2a21b1-70bd-4d5b-b8eb-2e6c2f4ff3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eea6d643-d50c-4b9f-ab32-d44e30b8e92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>4de414a7-5b9d-4fa2-aef0-99a8ab03a8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestFrm_lastname</value>
      <webElementGuid>7c6ed261-e84d-478c-972c-ff58ef6b5aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>8350d3ca-a6ed-4ec7-94bd-269b72baf8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestFrm_lastname&quot;)</value>
      <webElementGuid>9d42e8b6-e6b0-4c04-ab6e-37fde78792a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestFrm_lastname']</value>
      <webElementGuid>e175914c-9e23-4236-940a-2f0580605292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='guestFrm']/div/fieldset/div[2]/div/input</value>
      <webElementGuid>0995488c-a67e-4073-b4e3-0bab2a03c030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a097dae4-1851-4d6a-ba1e-f16934411663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lastname' and @id = 'guestFrm_lastname']</value>
      <webElementGuid>f8d1c25a-323c-458f-ab02-c0c9374c9ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
