<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InputZIP</name>
   <tag></tag>
   <elementGuidId>9fd178c1-11b6-429a-bab2-0ddcd6ca6496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimate_postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='estimate_postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#estimate_postcode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>863f3259-b9f1-4ced-bd74-b60f22828d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2eefb803-0d47-41d3-8dee-a04e872e90cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>6426bc1a-3cf1-46c0-94fd-02bed70a603d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimate_postcode</value>
      <webElementGuid>88f03cc2-935c-412e-9b09-df6167598de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control short</value>
      <webElementGuid>3489fdf8-c0bb-4052-8439-9dbd66689292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimate_postcode&quot;)</value>
      <webElementGuid>1bd22eaf-694c-4baa-8119-b0c167e46f57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='estimate_postcode']</value>
      <webElementGuid>dc645399-f5dc-4ff8-9dea-f1f944915fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='estimate']/div[2]/div/input</value>
      <webElementGuid>3b422913-7943-4195-be77-04d7aea80417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>21f0cb1a-78a0-4dc5-b25a-40af44ab6bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'postcode' and @id = 'estimate_postcode']</value>
      <webElementGuid>570b7ec1-74e7-4746-b9dd-e2ff52eaa71d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
