<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductPrice2</name>
   <tag></tag>
   <elementGuidId>b808f6f4-e1a1-4870-8c4a-48cdb87693e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cart']/div/div/table/tbody/tr[3]/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$14.00&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e033ecae-f901-4d54-92f0-b58f84717229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align_right</value>
      <webElementGuid>158fe908-772b-410d-b17a-9afd80dcd1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$14.00</value>
      <webElementGuid>e6500c8e-0714-455d-a0ae-d8d6d2975e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart&quot;)/div[@class=&quot;contentpanel&quot;]/div[@class=&quot;container-fluid cart-info product-list&quot;]/table[@class=&quot;table table-striped table-bordered&quot;]/tbody[1]/tr[3]/td[@class=&quot;align_right&quot;]</value>
      <webElementGuid>189f48df-7eb6-4c9b-961e-47d2f1f050f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cart']/div/div/table/tbody/tr[3]/td[6]</value>
      <webElementGuid>9e0fc634-60a9-4291-b105-56ece3530952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$14.00'])[2]/following::td[2]</value>
      <webElementGuid>9f91e4a4-ffc8-40e5-af63-e3e0645be0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ck one shock for him Deodorant'])[2]/following::td[4]</value>
      <webElementGuid>b157969a-d034-40ce-a097-0dee0d737f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Coupon Code'])[1]/preceding::td[2]</value>
      <webElementGuid>b2daec67-0545-4545-9880-393f0ffa1e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]</value>
      <webElementGuid>f1eb1367-deda-4302-857c-ac0e4441e20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$14.00' or . = '$14.00')]</value>
      <webElementGuid>cde1d189-999a-4714-b7a3-56a9160cb0ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
