<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StateSelector</name>
   <tag></tag>
   <elementGuidId>3dfa64d4-d75a-45ca-9207-a2464c2e0b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#estimate_country_zones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='estimate_country_zones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#estimate_country_zones</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d09ea15-46c0-43bc-8992-4a575a0ef170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country_zones[]</value>
      <webElementGuid>9d3b9bea-cf8f-4d48-852f-c5146f66408c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>estimate_country_zones</value>
      <webElementGuid>c0b15154-1f6b-4af2-affa-bbccc2ae4cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>4384120b-a176-4b8f-bb66-8ef5c0be72bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham</value>
      <webElementGuid>00d3cc7b-a648-45c9-83db-c67a76e7d2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimate_country_zones&quot;)</value>
      <webElementGuid>045c4ed7-438d-4668-b6e1-8cebd5c4dfed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='estimate_country_zones']</value>
      <webElementGuid>c9e31f61-5296-4a17-956b-cee5804dca1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='estimate']/div/div/div[2]/select</value>
      <webElementGuid>f2a7c721-71b7-4d5e-abb1-d583c5c49aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country and State'])[1]/following::select[2]</value>
      <webElementGuid>e126cfd3-2ca5-4149-b52c-6d1d3d914596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimate Shipping &amp; Taxes'])[1]/following::select[2]</value>
      <webElementGuid>30ad4587-d49a-47b2-81d8-98f386e03ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP/Post Code'])[1]/preceding::select[1]</value>
      <webElementGuid>dad6b830-4c3d-4c7e-b5fb-d9bc77fb082e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>fc49a411-2e8e-4db8-aa9b-2e5b6c1444ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'country_zones[]' and @id = 'estimate_country_zones' and (text() = ' --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham' or . = ' --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham')]</value>
      <webElementGuid>eed973e1-4c2a-4376-a9e4-18df1941db43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
