<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubTotal</name>
   <tag></tag>
   <elementGuidId>ff3d53af-9045-420b-beff-c53806bf8b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='totals_table']/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#totals_table > tbody > tr > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;$43.50&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3e548d4a-01b0-4007-a623-2365eedf0922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$43.50</value>
      <webElementGuid>cef1b83f-5286-42be-8a8e-ba5e38870ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totals_table&quot;)/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>2433b531-1aaf-48b5-8765-7b1581773d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='totals_table']/tbody/tr/td[2]</value>
      <webElementGuid>8dcb8b19-f3f0-4efc-b288-ceb5e853e9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-Total:'])[2]/following::td[1]</value>
      <webElementGuid>a6f4dfe8-e2e2-49b9-b9cf-2778ed689a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipments'])[1]/following::td[2]</value>
      <webElementGuid>2c25f8c2-79d0-4138-ac87-d86c6a72b32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Shipping Rate:'])[1]/preceding::td[1]</value>
      <webElementGuid>f26b2e70-977c-4121-9925-d748afb3e92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td[2]</value>
      <webElementGuid>cecf861a-e2ea-434f-a8da-b82aeae4a063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '$43.50' or . = '$43.50')]</value>
      <webElementGuid>9d6a7e98-89c3-4540-9f1c-f58fe6ec8016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
