<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_38.00</name>
   <tag></tag>
   <elementGuidId>cee8029a-4b92-4315-8700-156ee4d6ebb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product']/fieldset/div[2]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.total-price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#product >> internal:text=&quot;$38.00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>25f4cae0-9cc5-48da-b35d-4b3273765392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>total-price</value>
      <webElementGuid>6f167f6a-56bc-45e7-8fb4-0a42ce4cfa39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$38.00</value>
      <webElementGuid>26998efe-47ab-4d85-8bab-4420b9ffaf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product&quot;)/fieldset[1]/div[@class=&quot;form-group mt20 mb10 total-price-holder&quot;]/label[@class=&quot;control-label&quot;]/span[@class=&quot;total-price&quot;]</value>
      <webElementGuid>5e07f176-0685-4a2e-8852-3fc48785d39f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product']/fieldset/div[2]/label/span</value>
      <webElementGuid>3a4293aa-a6e8-4288-8809-c05fcf7dc363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty:'])[1]/following::span[1]</value>
      <webElementGuid>1bdd2afb-f30f-4b9d-a48f-8d2128da3331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::span[1]</value>
      <webElementGuid>cc82d4d4-03cb-4f10-aff7-ca77425f97cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>fbb913fe-90ce-4915-9842-885ddd8f0922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$38.00' or . = '$38.00')]</value>
      <webElementGuid>59c76877-c29f-411f-b60e-69e00101e921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
