<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MainMenu</name>
   <tag></tag>
   <elementGuidId>383cdd0f-2652-4047-b10b-6e6f54a28c3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.form-control</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Main Menu Specials Account Login Check Your Order Cart Checkout' or . = 'Main Menu Specials Account Login Check Your Order Cart Checkout')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topnav']/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d66047b3-02a1-4227-8a34-9ecaf9d7ac50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>da10b7d8-49d0-4662-8fef-eef2063c7bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Main Menu Specials Account Login Check Your Order Cart Checkout</value>
      <webElementGuid>67c77e4f-e517-4057-90eb-c8e8b128fb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav&quot;)/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e185d025-4e0d-44ca-8719-b44d786c85fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topnav']/select</value>
      <webElementGuid>55a92041-c7d7-4a40-85cb-7e378f961a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::select[1]</value>
      <webElementGuid>168555c9-d95e-470c-a404-a5e94b7c91bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::select[1]</value>
      <webElementGuid>5bd0f5b1-896a-4251-8332-07a73e5938d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[1]/preceding::select[1]</value>
      <webElementGuid>302b9816-7a09-41b2-a214-3c01fb62a2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[2]/preceding::select[1]</value>
      <webElementGuid>f30e1d59-ee66-49d6-a898-4533ffcf3050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3ec92491-b15d-464d-933e-6a1c4e0d8bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Main Menu Specials Account Login Check Your Order Cart Checkout' or . = 'Main Menu Specials Account Login Check Your Order Cart Checkout')]</value>
      <webElementGuid>c7da4a47-88dd-4e94-965b-c59bb60aadaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
