<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FooterLogoff</name>
   <tag></tag>
   <elementGuidId>5bec88f2-853d-4b58-81ef-0d4c42a5ec9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer']/footer/section[2]/div/div/div/ul/li[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.info_links_footer > li:nth-of-type(7) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logoff&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4703dc7-d172-44aa-b5fc-c5da4c5c6379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=account/logout</value>
      <webElementGuid>f8e71dad-9ed0-488f-b029-59c783e07a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logoff</value>
      <webElementGuid>4852bffa-8539-4d3f-b253-b98811802014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/footer[1]/section[@class=&quot;footerlinks&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;pull-left&quot;]/div[@class=&quot;info&quot;]/ul[@class=&quot;info_links_footer&quot;]/li[7]/a[1]</value>
      <webElementGuid>ff0873d4-74d1-4c10-a11d-517db7b2ec3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/footer/section[2]/div/div/div/ul/li[7]/a</value>
      <webElementGuid>f7a40287-006c-47da-95ad-9974c184be07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Logoff')])[2]</value>
      <webElementGuid>520f32cd-9f6d-42e9-ae9f-fa606ad97e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Map'])[1]/following::a[1]</value>
      <webElementGuid>a0201107-0519-4eb2-bb6a-7645a7a65ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::a[2]</value>
      <webElementGuid>f1a361e5-c196-4299-af96-8e8f823f1588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[3]/preceding::a[1]</value>
      <webElementGuid>ef9d36a3-a1e3-4631-8f47-bade4947ad0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basket'])[2]/preceding::a[2]</value>
      <webElementGuid>670bb5e3-c61b-4077-af85-6b2d75f415f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logoff']/parent::*</value>
      <webElementGuid>599cd6f0-0245-42e1-ad3c-ed2f5b941860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://automationteststore.com/index.php?rt=account/logout')])[4]</value>
      <webElementGuid>f7b823bc-ee52-4fa6-9a02-f9673c851896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul/li[7]/a</value>
      <webElementGuid>0def2d35-8024-46bc-99d3-548f259389e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=account/logout' and (text() = 'Logoff' or . = 'Logoff')]</value>
      <webElementGuid>f6751fd2-168f-4486-8cb0-2ad9663f9ccd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
