<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GuestCheckoutSelect</name>
   <tag></tag>
   <elementGuidId>ca04ce63-5f16-4a3a-a4de-11c77a0fb2fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountFrm_accountguest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountFrm_accountguest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Guest Checkout&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fc3ad48-7135-430e-9077-2b5bae10d8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountFrm_accountguest</value>
      <webElementGuid>2f57649e-1ae9-4d76-986d-250343587cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>43bab005-ae16-4116-a1fe-f610258301fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>guest</value>
      <webElementGuid>3423f7bc-2b09-4c8f-afe3-d6261c632607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account</value>
      <webElementGuid>a2c5c2fa-8a42-46d2-8134-1d1c65581c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountFrm_accountguest&quot;)</value>
      <webElementGuid>ea79c6de-b40f-4d49-bf97-7aa8d86c9ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountFrm_accountguest']</value>
      <webElementGuid>6f83f899-7f7d-462c-8770-3376cce843a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='accountFrm']/fieldset/div[2]/label/input</value>
      <webElementGuid>89c1b676-13c0-41e7-be56-db67bd490e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>62699a3d-d2a3-4cc7-977f-4362bb009777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accountFrm_accountguest' and @type = 'radio' and @name = 'account']</value>
      <webElementGuid>1e544cc1-db8b-4cd6-b537-c5f8a2ef7175</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
