<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginPassword</name>
   <tag></tag>
   <elementGuidId>32cca86f-6e7a-41d0-8327-954e49f76342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginFrm_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginFrm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loginFrm_password</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adcfbe3a-17be-4c5c-a63c-bc85771fdade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0219cd12-224f-488b-a2ec-5e3d94178e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>26493831-4c56-4417-94d4-ef96a58f392e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginFrm_password</value>
      <webElementGuid>b751771f-9d53-4748-8b42-360df1fd0ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>8ceb91c8-af9c-48aa-aa41-d6cc0cdfb4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFrm_password&quot;)</value>
      <webElementGuid>ac5faaf0-2e00-45a0-8530-ebe694a9738e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginFrm_password']</value>
      <webElementGuid>08009f83-3b97-4c15-ba47-61ec209a291a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginFrm']/fieldset/div[2]/div/input</value>
      <webElementGuid>61ff352d-71f1-4917-92b5-ce58887b5612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>874a146f-aa65-480e-bdc1-6766c16bc6c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'loginFrm_password']</value>
      <webElementGuid>b5e340ae-9e36-477d-a117-d369545c3a93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
