<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginName</name>
   <tag></tag>
   <elementGuidId>aed697f3-1177-4841-b4fe-e62f598f0fb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginFrm_loginname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginFrm_loginname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loginFrm_loginname</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee6e3b6b-8520-4f35-b6bb-9e51b6590ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2911ba69-e727-4ac2-b853-689b729c8aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginname</value>
      <webElementGuid>68343c21-f511-4f61-92ac-13eaaa6b4daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginFrm_loginname</value>
      <webElementGuid>41cb7871-3b76-466f-a3a9-279b227b54ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>dd1afe95-c129-49e9-9579-8e038c1cc0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFrm_loginname&quot;)</value>
      <webElementGuid>06f4495f-259c-4311-ba58-56ca8d1fbc19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginFrm_loginname']</value>
      <webElementGuid>e8f7c418-363d-47f8-86b1-fa69e008d620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginFrm']/fieldset/div/div/input</value>
      <webElementGuid>37d9c38e-579f-4472-a7a3-5aabf522bca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>c97811e1-a80b-4d66-b18b-f4aa287ecd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'loginname' and @id = 'loginFrm_loginname']</value>
      <webElementGuid>4573da08-3cc2-4960-b746-cf0ef499c556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
