<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_green_option347</name>
   <tag></tag>
   <elementGuidId>14b0403d-ff7d-41eb-b8eb-d64fd0a780b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option347765</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='option347765']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;green&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f54e474d-bdeb-41a9-aca9-8839674a654c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option347765</value>
      <webElementGuid>a851e303-8de2-44c7-8dab-e2a4ba122bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cbfecb94-1853-4f91-a736-3cda33e43c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>765</value>
      <webElementGuid>e13d7645-9769-4db5-9601-be58259658bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option[347][]</value>
      <webElementGuid>c9a27b74-ebd7-4bbf-b4ab-a3aca3f4129d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option347765&quot;)</value>
      <webElementGuid>d13d1074-1a1e-441b-b9dc-8cf5b3fad0d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='option347765']</value>
      <webElementGuid>66016a37-cf05-4643-aae8-eebd66f46e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product']/fieldset/div/div/label[3]/input</value>
      <webElementGuid>9eec987c-9d25-4e40-848f-40aed232796f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]/input</value>
      <webElementGuid>0548b5d2-ed07-41b9-a33a-66ac3c0fe3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'option347765' and @type = 'radio' and @name = 'option[347][]']</value>
      <webElementGuid>9892a3ee-d73c-493c-baa0-ea42aa87541c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
