<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Out of Stock</name>
   <tag></tag>
   <elementGuidId>4909d13d-4dec-49f7-b91b-1a0525cd7dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.nostock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_frame_featured_1769']/div/div[2]/div[2]/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#block_frame_featured_1769 >> internal:text=&quot;Out of Stock&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c9ac847-b99a-4cf0-9930-dce972220c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nostock</value>
      <webElementGuid>bd9ccf18-bc1d-42a1-a923-5a3f91e8b5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Out of Stock</value>
      <webElementGuid>02d3a417-4e9e-419d-8832-b71e96e8f243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_frame_featured_1769&quot;)/div[@class=&quot;thumbnails list-inline&quot;]/div[@class=&quot;col-md-3 col-sm-6 col-xs-12&quot;]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;pricetag jumbotron&quot;]/span[@class=&quot;nostock&quot;]</value>
      <webElementGuid>4891a853-f209-484f-95b3-6b23e10bfcb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_frame_featured_1769']/div/div[2]/div[2]/div[3]/span</value>
      <webElementGuid>2275f5b7-f6b8-4776-af67-7f9e655f58f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Review'])[2]/following::span[1]</value>
      <webElementGuid>1cef34d3-6e57-4e7e-a6a7-3023c35c7261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/following::span[1]</value>
      <webElementGuid>8e17d8ed-9f84-4ea2-8255-35474816ced6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$19.00'])[1]/preceding::span[1]</value>
      <webElementGuid>eda46139-66b7-4b68-b360-f40f0afb0bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$30.00'])[1]/preceding::span[1]</value>
      <webElementGuid>7c6c7d40-803b-4bc2-9ce9-11c24fd78eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Out of Stock']/parent::*</value>
      <webElementGuid>e5e9d57a-9871-45e6-aa35-41977844fa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>99216a70-24f0-406b-af85-912541b7318f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Out of Stock' or . = 'Out of Stock')]</value>
      <webElementGuid>70cff3cd-1011-4120-ba6a-f30276e202a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
